#! /bin/sh

# Do not set -e because it's easier if most commands still run even when one fails
#set -e

cd ~
if [[ $SHELL == *"zsh"* ]]; then
    echo 'Using zsh'
    CONFIGFILE=~/.zshrc
else
    echo 'Using bash'
    CONFIGFILE=~/.bashrc
fi

echo "Using CONFIGFILE $CONFIGFILE"

echo '' >> $CONFIGFILE
echo '# ALIASES from UTILS' >> $CONFIGFILE
echo 'source ~/.utils/bashrc/git-alias' >> $CONFIGFILE
echo 'source ~/.utils/bashrc/workstation' >> $CONFIGFILE
echo '# Uncomment the relevant alias files'
echo '# source ~/.utils/bashrc/workstation__macos' >> $CONFIGFILE
echo '# source ~/.utils/bashrc/workstation__windows' >> $CONFIGFILE
echo '# source ~/.utils/bashrc/workstation__tara' >> $CONFIGFILE
echo '# source ~/.utils/bashrc/keyboard' >> $CONFIGFILE
echo '# source ~/.utils/bashrc/trackpad' >> $CONFIGFILE


touch ~/.utils/bashrc/only-this-machine
echo 'source ~/.utils/bashrc/only-this-machine' >> $CONFIGFILE
source $CONFIGFILE
echo "Please edit $CONFIGFILE and uncomment any alias files relevant to your machine"


####################################################
# XXX on macos nvim is installed in /usr/local/bin
# on gentoo, there is no sudo unless you install it
#sudo ln -s /usr/bin/nvim /usr/bin/vi
#sudo ln -s ~/.utils/scripts/screenshot /usr/bin

ln -s ~/.utils/Xmodmap ~/.Xmodmap

mkdir -p ~/.config
ln -s ~/.utils/terminator ~/.config/terminator

ln -s ~/.utils/gitconfig ~/.gitconfig

# Note nvim uses a different config path
# ln -s ~/.utils/vimrc/vimrc ~/.vimrc
ln -s ~/.utils/nvim ~/.config/nvim


# Some commands fail on macos, so we only apply them conditionally
if [[ "$(uname)" == "Darwin" ]]; then
  echo 'You will need to create an alias for neovim'
else
  sudo ln -s /usr/bin/nvim /usr/bin/vi
  sudo ln -s ~/.utils/scripts/screenshot /usr/bin/screenshot
fi


